### ISSUE TITLE
Rotavirus Flag :  Missing No site lab result is displaying red flag for EPI

### ISSUE THREAD

**Issue by ClaudiaOrtizD** [IBVPD/Nuvi#106]
Rotavirus Flag :  
Why "Missing No site lab result"  is displaying red flag for EPI?
![image](https://user-images.githubusercontent.com/23636063/59059170-4c551280-886c-11e9-8a2a-bafadccfcab2.png)

**Comment by gnat42** [comment]
The system expects all cases to have a 'Case' and a 'SiteLab' related data since typically the 'Site Lab' is a lab in the hospital so should always get something. Though I guess its possible for the case to take no samples and so the site lab wouldn't have anything either. Is that the situation above?

**Comment by ClaudiaOrtizD** [comment]
Yes, the situation is that there is no sample. It is not common.    I talked to Maria Teresa and said is ok to leave it red or orange in this case
