### ISSUE TITLE
Missing variables when exporting data -Vinuva Meningitis

### ISSUE THREAD

**Issue by ClaudiaOrtizD** [IBVPD/Nuvi#117]
There is an issue in when exporting data of meningitis that is not exporting all the data .

The are 20 variables missing, I attached an excel that it shows the current and previous variables.
For instance, the following variables missing.  

siteLab.csf_wcc
siteLab.csf_protein
siteLab.csf_glucose

[meningitis-current and previous variables.xlsx](https://github.com/IBVPD/Nuvi/files/3590860/meningitis-current.and.previous.variables.xlsx)

**Comment by gnat42** [comment]
I've reviewed the excel sheet. There were a few missing variables for sure. I think I've got them all in there now. However some are gone because of changes to the data set. For example, the original seemed to try to export 
```
siteLab.rl_csf_sent
siteLab.rl_csf_date
siteLab.rl_isol_csf_sent
siteLab.rl_isol_csf_date
siteLab.rl_isol_blood_sent
siteLab.rl_isol_blood_date
siteLab.rl_broth_sent
siteLab.rl_broth_date
siteLab.rl_other_sent
siteLab.rl_other_date
```
However these fields don't exist in the Meningitis data set. It seems it used to exist in the IBD data set but were likely removed since sitelabs don't send samples to the RRL lab? In any case all the other missing fields should now be there.
